name: API Smoke

on:
  workflow_dispatch:

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Quick API smoke
        run: |
          set -euo pipefail
          BASE="https://ttvizaup00.execute-api.us-east-1.amazonaws.com"
          SID="sub_test_manual"
          echo "GET $BASE/score/$SID"
          curl -sS "$BASE/score/$SID" | jq -r '.submission_id, .overall.sum' | sed -n '1,4p'
          echo "POST $BASE/analyze/$SID"
          curl -sS -X POST "$BASE/analyze/$SID" -H 'Content-Type: application/json' -d '{}' | jq -r '.status // "ok"' | sed -n '1,2p'

