name: Python Tests

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r api/requirements.txt
          if [ -f api/requirements-dev.txt ]; then pip install -r api/requirements-dev.txt; fi

      - name: Run unit tests
        run: pytest -q

